Media-XI/artscope-backend

src/main/java/com/example/codebase/controller/AuthController.java, src/main/java/com/example/codebase/domain/auth/handler/OAuth2AuthenticationSuccessHandler.java, src/main/java/com/example/codebase/util/SecurityUtil.java, src/test/java/com/example/codebase/controller/ArtworkControllerTest.java
- JWT 액세스 토큰 발급 시 응답 Body와 함께 Set-Cookie를 이용해 Cookie에 저장합니다.
- Secure, HttpOnly를 이용해 토큰 탈취 가능성을 줄였습니다.
=> [PR] acces token Set-Cookie 기능 추가

src/main/java/com/example/codebase/domain/post/repository/PostCommentRepository.java, src/main/java/com/example/codebase/domain/post/service/PostService.java
- TransientObjectException: object references an unsaved transient instance - save the transient instance before flushing -> 해결
- 기존 : 새로운 댓글 저장 로직엔 부모 연관관계에 매핑, 추가만 하고 새로운댓글을 저장하는 코드가 없어서 트랜잭션 예외 처리가 발생
- 이후 : 새로운 댓글 저장 로직에 save(newComment) 코드 추가
- 또한 다른 게시글의 댓글을 부모로하는 대댓글 생성 예외처리 적용
=> [PR] 대댓글 생성이 안되는 에러 해결

src/main/java/com/example/codebase/domain/post/entity/Post.java, src/main/java/com/example/codebase/domain/post/service/PostService.java, src/test/java/com/example/codebase/controller/PostControllerTest.java
- 이전 : Post Comment가 1차 댓글수만 반환
- 이후 : Post 내부 모든 댓글 수 반환
-  일부 코드가 포맷팅되었습니다.
기존에는 Lombok Getter 인해 자동으로 생성되는 getComments() 를 사용하고 있었지만 오버라이딩하여 1차 댓글 수 + 2차 댓글수를 함께 반환하도록 개선했습니다.
=> [PR] Feed 생성 시 Post의 Commets가 일치하지 않는 이슈 해결

src/main/java/com/example/codebase/controller/PostController.java, src/main/java/com/example/codebase/domain/post/entity/Post.java, src/main/java/com/example/codebase/domain/post/repository/PostCommentRepository.java, src/main/java/com/example/codebase/domain/post/service/PostService.java, src/test/java/com/example/codebase/controller/PostControllerTest.java
- 댓글 삭제 시 DTO 반환
- 해당 게시글의 댓글 수를 가져오는 쿼리 작성 및 사용
- 부모 엔티티에서 자식 엔티티를 삭제하도록 개선
=> [PR] 댓글 삭제 시 갯수가 불일치하는 현상 해결

src/main/java/com/example/codebase/domain/post/dto/PostResponseDTO.java, src/main/java/com/example/codebase/domain/post/dto/PostWithLikesResponseDTO.java
PostWithLikesResponseDTO (Post DTO에 Like 관련 정보가 더해진 DTO)에 media가 포함되지 않는 이슈를 해결했습니다.
- 기존에는 생성자가 아닌 정적 팩토리 메소드 from을 통해서 데이터를 set 했었는데 개선 이후에는 생성자를 통해서 DTO를 세팅하도록 하였습니다.
- Post 를 매개변수로 받는 생성자를 생성했습니다.
=> [PR] fix: PostResponseDTO media가 null인 이슈 해결

src/main/java/com/example/codebase/domain/exhibition/dto/EventScheduleCreateDTO.java, src/main/java/com/example/codebase/domain/exhibition/dto/EventScheduleResponseDTO.java, src/main/java/com/example/codebase/domain/exhibition/dto/ExhibitionDetailResponseDTO.java, src/main/java/com/example/codebase/domain/exhibition/dto/ExhibitionSearchDTO.java, src/main/java/com/example/codebase/domain/exhibition/dto/ParticipantInformationDTO.java, src/main/java/com/example/codebase/domain/exhibition/dto/ParticipantInformationResponseDTO.java, src/main/java/com/example/codebase/domain/exhibition/service/ExhibitionService.java, src/test/java/com/example/codebase/controller/ExhibitionControllerTest.java
- Exhibition이 time으로 변경됨에 따라 조회가 제대로 안되던 문제를 해결했습니다.
- test코드에서 고정된 eventSchedule값을 현재시간을 기준으로 하도록 수정했습니다. (00초로 설정합니다)
- Exhibition 상세조회시 작성자의 프로필,정보가 반환됩니다.
- ExhibitionParticipant이 제대로 입력, 반환이 안되던 문제를 해결했습니다.
=> Fix/exhibition 조회 안되는 문제

src/main/java/com/example/codebase/controller/MemberController.java, src/main/java/com/example/codebase/domain/member/dto/CreateArtistMemberDTO.java, src/main/java/com/example/codebase/domain/member/dto/CreateCuratorMemberDTO.java, src/main/java/com/example/codebase/domain/member/dto/CreateMemberDTO.java, src/main/java/com/example/codebase/domain/member/dto/MemberResponseDTO.java, src/main/java/com/example/codebase/domain/member/dto/UpdateMemberDTO.java, src/main/java/com/example/codebase/domain/member/entity/Member.java, src/main/java/com/example/codebase/domain/member/repository/MemberRepository.java, src/main/java/com/example/codebase/domain/member/service/MemberService.java, src/main/resources/db/migration/V202312081539__add_allow_email_receive_column_to_member.sql, src/test/java/com/example/codebase/controller/MemberControllerTest.java
- 회원 정보 수정 시 history size와 가입 시 size가 상이하므로 통일 (수정 : 250자, 가입 : 1000자)
- 회원 가입 시 이메일 수신 여부 받습니다.
- 이메일 수신 여부를 변경할 수 있는 API가 새롭게 추가됩니다. 
- 검색 엔진 용 username 리스트 조회 API 가 새롭게 추가됩니다.
자세한 구현 내용은 [Jira Ticket](https://mediaxi.atlassian.net/jira/software/projects/ARTDEV/boards/1?selectedIssue=ARTDEV-86)을 참고해주세요
=> [ARTDEV-86] 회원 관련 정보 사이즈와 승인 여부 추가, 새로운 SEO 전용 API, 그외 수정 사항

src/main/java/com/example/codebase/controller/MemberController.java, src/main/java/com/example/codebase/domain/member/dto/PasswordResetRequestDTO.java, src/main/java/com/example/codebase/domain/member/service/MemberService.java
- 비밀번호 재설정 시 이전 비밀번호, 새로운 비밀번호에 대한 검증 로직이 추가되었습니다.
- 인증 코드 삭제 로직을 검증 이후로 위치를 변경했습니다.
- Password Reset 요청 DTO를 파라미터로 받도록 코드를 수정했습니다.
=> 비밀번호 재설정 API 이전 비밀번호 검증 로직 추가 및 내부 구현 수정

src/main/java/com/example/codebase/domain/exhibition/entity/Event.java
- LocalDate로 변환할 문자열 형식을 알려주도록 코드를 수정했습니다.
크롤링 후 다시 요청을 보내면 "20231214" 문자열을 LocalDate.parse() 시 포맷을 지정하지 않아 에러가 발생하는데 이를 해결했습니다.
`java.time.format.DateTimeParseException: Text '20231214' could not be parsed at index 0`
=> fix: Event 수정 여부 체크 시 LocalDate.parse() 에러 해결

src/main/java/com/example/codebase/domain/exhibition/crawling/service/ExhibitionCrawlingService.java
- 공공 데이터 포털에서 100개씩 공연전시 목록을 조회할수 있도록 수정했습니다.
=> fix: 공공데이터 포털에서 100개씩 전시 공연 정보 목록 조회

src/main/java/com/example/codebase/domain/exhibition/repository/EventRepository.java, src/main/java/com/example/codebase/domain/feed/dto/FeedItemEventResponseDto.java, src/main/java/com/example/codebase/domain/feed/dto/FeedItemResponseDto.java, src/main/java/com/example/codebase/domain/feed/dto/FeedType.java, src/main/java/com/example/codebase/domain/feed/service/FeedService.java
- 피드 생성 시 이벤트 데이터를 조회하는 쿼리를 크롤링 한 이벤트는 가져오지 않도록 수정했습니다.
- 피드 생성 시 Exhibition 이 Deprecated 됨에 따라 관련 로직을 Event 객체로 사용하도록 변경했습니다.
- Exhibition과 호환할 수 있도록 기존 코드를 수정했습니다.
- Exhibition 관련 피드 로직에 @Deprecated 이 부착되었습니다.
=> 피드에 크롤링된 이벤트 노출하지 않도록 수정

src/main/java/com/example/codebase/domain/exhibition/dto/EventDetailResponseDTO.java, src/main/java/com/example/codebase/domain/exhibition/dto/EventResponseDTO.java
- event를 전체 조회할때 exhibition이 반환되던 문제를 해결했습니다.
- 이제 event를 상세조회할때 thumbnail도 media에 포함됩니다.
=> fix: 이벤트 전체 조회, 상세조회 dto 문제 해결

src/main/java/com/example/codebase/controller/MagazineCategoryController.java, src/main/java/com/example/codebase/controller/MagazineController.java, src/main/java/com/example/codebase/controller/MagazineLikeController.java, src/main/java/com/example/codebase/domain/magazine/dto/MagazineCommentRepsonse.java, src/main/java/com/example/codebase/domain/magazine/dto/MagazineCommentRequest.java, src/main/java/com/example/codebase/domain/magazine/dto/MagazineRequest.java, src/main/java/com/example/codebase/domain/magazine/dto/MagazineResponse.java, src/main/java/com/example/codebase/domain/magazine/entity/Magazine.java, src/main/java/com/example/codebase/domain/magazine/entity/MagazineComment.java, src/main/java/com/example/codebase/domain/magazine/entity/MagazineLike.java, src/main/java/com/example/codebase/domain/magazine/repository/MagazineCommentRepository.java, src/main/java/com/example/codebase/domain/magazine/repository/MagazineLikeRepository.java, src/main/java/com/example/codebase/domain/magazine/repository/MagazineRepository.java, src/main/java/com/example/codebase/domain/magazine/service/MagazineLikeService.java, src/main/java/com/example/codebase/domain/magazine/service/MagazineService.java, src/main/java/com/example/codebase/util/SecurityUtil.java, src/main/resources/application-test.yml, src/main/resources/db/migration/V202402151700__create_magazine_comment.sql, src/main/resources/db/migration/V202402291700__create_magazine_like_table.sql, src/test/java/com/example/codebase/controller/MagazineControllerTest.java, src/test/java/com/example/codebase/controller/MagazineLikeControllerTest.java
- 매거진 댓글 생성, 삭제, 수정 API
- 매거진 좋아요, 좋아요 취소 API
- 좋아요 API 멱등성 보장 [로직](https://github.com/Media-XI/artscope-backend/pull/128/commits/4a96f162b8ac51e00d412e9217e3c0cbdb93f7c4) 
- 매거진 조회 시 조회수 증가 기능 
- 매거진 좋아요, 조회수 수에 대해 동시성 테스트 필요
- 한 유저가 매거진 좋아요 2번 이상 (따닥) 동시에 요청 시 한 요청은 성공하고 나머지 요청에 대해선 실패할 수 있도록 로직 개선 (연달아 요청이 아닌 동시에)
- 매거진 조회 시 좋아요 여부 표시 필요
=>  매거진 댓글, 좋아요, 조회수 기능 구현

src/main/java/com/example/codebase/controller/MagazineController.java, src/main/java/com/example/codebase/domain/magazine/dto/MagazineRequest.java, src/main/java/com/example/codebase/domain/magazine/dto/MagazineResponse.java, src/main/java/com/example/codebase/domain/magazine/entity/Magazine.java, src/main/java/com/example/codebase/domain/magazine/repository/MagazineRepository.java, src/main/java/com/example/codebase/domain/magazine/service/MagazineService.java, src/main/resources/db/migration/V202403041730__add_metadata_column_to_magazine.sql, src/test/java/com/example/codebase/controller/MagazineControllerTest.java
- 매거진 메타데이터 필드가 추가되었습니다
- 이제 JSON 형식으로 매거진의 메타데이터를 추가할 수 있습니다.
- 매거진 수정 API의 형식이 변경되었습니다.
- 기존 데이터를 포함해서 업데이트 되는 수정 로직에 따라 Patch 방식이 아닌 Put 방식으로 변경되었습니다.
- 업데이트 시 메타데이터를 수정할 수 있습니다.
- 사용자가 작성한 매거진 조회 API 가 구현되었습니다. 
연관된 티켓 : [ARTDEV-149](https://mediaxi.atlassian.net/jira/software/projects/ARTDEV/boards/1?selectedIssue=ARTDEV-149), [ARTDEV-148](https://mediaxi.atlassian.net/jira/software/projects/ARTDEV/boards/1?selectedIssue=ARTDEV-148)
[ARTDEV-149]: https://mediaxi.atlassian.net/browse/ARTDEV-149?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ARTDEV-148]: https://mediaxi.atlassian.net/browse/ARTDEV-148?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> 매거진 메타데이터 다이나믹 필드 & 사용자가 작성한 매거진 조회 API

src/main/java/com/example/codebase/annotation/DistributedLock.java, src/main/java/com/example/codebase/aop/DistributedLockAop.java, src/main/java/com/example/codebase/domain/post/entity/Post.java, src/main/java/com/example/codebase/domain/post/service/PostService.java, src/test/java/com/example/codebase/domain/post/service/PostServiceTest.java
**문제 상황**
1. 낙관적 락으로 인해 여러 트랜잭션 접근 시 ObjectOptimisticLockingFailureException 발생
2. 실제 DB 반영값과 예측값이 불일치하는 문제가 발생
- 분산락과 별도의 트랜잭션이 적용된 로직이 문제, 분산락 트랜잭션 커밋 후 락을 반환하는데 이때 다른 트랜잭션이 락을 얻게되고 이전 데이터를 가져오므로 갱신 손실 문제가 발생함
문제되는 코드
```java
@DistributedLock
@Transactional
public void like() {
...
```
**문제 해결**
1. 낙관적 락 구현 제거
2. 분산락 트랜잭션만 사용하도록 로직 수정
해당 문제는 별도의 트랜잭션 어노테이션을 제거하고 분산락 어노테이션 사용 시 트랜잭션 여부 옵션을 제공하여 별도로 트랜잭션을 내부적으로 처리하도록 설정함
=> 동시성 테스트 실패 문제 해결

src/main/java/com/example/codebase/domain/magazine/dto/MagazineResponse.java, src/main/java/com/example/codebase/domain/magazine/entity/MagazineWithIsLiked.java, src/main/java/com/example/codebase/domain/magazine/repository/MagazineRepository.java, src/main/java/com/example/codebase/domain/magazine/service/MagazineService.java, src/main/java/com/example/codebase/util/SecurityUtil.java, src/test/java/com/example/codebase/controller/MagazineLikeControllerTest.java
매거진 전체/단일 조회 시 로그인 한 사용자의 좋아요 여부를 포함한 기능을 개발했습니다.
- SecurityUtil을 컨트롤러 레이어가 아닌 서비스 레이어에서 호출 및 값을 전달하도록 개발해봤습니다.
- **AS-IS** 컨트롤러에서 유틸 클래스 사용, 파라미터 전달, 이를 통한 비즈니스 로직 분기 (로그인했을때, 로그인안했을때)
- **TO-BE** 서비스에서 유틸 클래스 사용, 파라미터 전달, Repository 에서 default 메서드를 사용한 DB 조회 로직 분기 (로그인했을때, 로그인안했을때)
- 유틸성 기능을 제공하는 클래스이므로 어느 계층에서 호출해야한다는 책임이 분명하지 않습니다. 따라서 이번 기능을 개발하면서 해당 값 (로그인 정보)를 실제로 사용하는 로직과 가까이 함으로 더욱 가독성이 높은 코드를 기대할 수 있었습니다.
- MagazineRepository 인터페이스에서 default 메서드를 이용해 DB 조회 분기 로직 책임을 서비스가 아닌 DB 단에 가깝게 위치해 개발했습니다.
- 서비스 레이어는 DB에 대해 어떤식으로 조회를 해야하는지 해당 책임을 Repository에서 수행해 기존 비즈니스 레이어의 코드를 해치지않고, Repository 레이어에서 로그인 여부에 따른 조회 방식을 분기할 수 있습니다.
- 해당 방식을 통해 좋아요 여부를 조회하는 메서드를 재활용할 수 있고, 유지보수하기 쉬운 코드를 기대할 수 있습니다.
- SecurityUtil의 getCurrentUsername 메서드 내부 로직이 변경되었습니다.
- Optional로 반환값을 래핑하다보니, 분기가 필요한 부분에서 …
=> [PR] 좋아요한 매거진 표시 기능

src/main/java/com/example/codebase/annotation/CheckDuplicatedRequest.java, src/main/java/com/example/codebase/aop/CheckDuplicatedRequestAspect.java, src/main/java/com/example/codebase/controller/MagazineController.java, src/main/java/com/example/codebase/domain/magazine/dto/MagazineRequest.java, src/main/java/com/example/codebase/domain/magazine/dto/MagazineResponse.java, src/main/java/com/example/codebase/domain/magazine/entity/Magazine.java, src/main/java/com/example/codebase/domain/magazine/repository/MagazineRepository.java, src/main/java/com/example/codebase/domain/magazine/service/MagazineService.java, src/main/java/com/example/codebase/domain/team/entity/Team.java, src/main/java/com/example/codebase/domain/team/service/TeamService.java, src/main/resources/db/migration/V202403051158__application.sql, src/test/java/com/example/codebase/aop/CheckDuplicatedRequestAspectMock.java, src/test/java/com/example/codebase/controller/CurationControllerTest.java, src/test/java/com/example/codebase/controller/MagazineCategoryControllerTest.java, src/test/java/com/example/codebase/controller/MagazineControllerTest.java
> 이번 PR에서 작업한 내용을 간단하게 설명해주세요.
1. 매거진 생성시 urn을 통하여 분기하여, 팀 매거진 또는 개인 매거진을 생성할 수 있도록 변경했습니다.
@PostMapping api/magazines
2. 매거진 조회시 쿼리 파라미터를 사용해 매거진 전체 조회, 개인 조회를 통합하고 팀도 조회할 수 있도록 추가했습니다.
@GetMapping api/magazines
3. 매거진이 동시에 두번 작성되는 것을 방지하는 코드를 작성했습니다.
-> 본래 follow와 같이 서비스 코드에서 방지 로직을 작성할려고 헀지만, 
```java
createMagazine(member)
createMagazine(member)
createMagazine(member)
```
이럴경우 테스트 시 항상 해당 중복된 요청에 걸리는 문제가 발생해서 어떻게 해결할지 고민을 했습니다.
-> 해당 요청에 대한 중복 검증은 서비스 보단 컨트롤러에 위치하는게 맞는것 같아서 aop를 활용하여 bean으로 등록한뒤. @CheckDuplicatedRequest을 컨트롤러 단에 위치 시켜서 해결했습니다.
~~기존코드~~
```java
private void checkDuplicatedRequest(MagazineRequest.Create magazineRequest, String username) {
String uniqueKey = username + "->" + magazineRequest.getTitle();
if (redisUtil.getData(uniqueKey).isPresent()) {
throw new …
```
=> feat 메거진 팀 글쓰기 기능

src/main/java/com/example/codebase/domain/member/dto/MemberResponseDTO.java, src/main/java/com/example/codebase/domain/member/entity/Member.java, src/main/java/com/example/codebase/domain/member/service/MemberService.java, src/main/java/com/example/codebase/domain/team/dto/TeamResponse.java, src/main/java/com/example/codebase/domain/team/dto/TeamUserResponse.java, src/main/java/com/example/codebase/domain/team/entity/TeamUser.java, src/test/java/com/example/codebase/controller/MemberControllerTest.java, src/test/java/com/example/codebase/controller/TeamControllerTest.java
- get /api/teams/members/{username} 에서 팀 id가 반환안되던 문제를 해결했습니다.
- get /api/members/profile/{username}, get  /api/members/profile 에서 자신이 속해있는 팀을 반환할 수 있도록 추가했습니다.
- memberService의  @transactional을 기존 Jakarta에서 springframework에서 제공해주는 어노테이션으로 변경했습니다.
[jirra이슈](https://mediaxi.atlassian.net/jira/software/projects/ART/issues/?jql=project%20%3D%20%22ART%22%20ORDER%20BY%20created%20DESC)
=> [PR] 팀 정보 반환 기능 추가

.github/workflows/test.yaml, src/main/java/com/example/codebase/controller/AuthController.java, src/main/java/com/example/codebase/controller/MemberController.java, src/main/java/com/example/codebase/domain/member/dto/MemberResponseDTO.java, src/test/java/com/example/codebase/controller/AuthControllerTest.java, src/test/java/com/example/codebase/controller/MemberControllerTest.java
- 내 정보 조회 API 가 AuthController 에서 처리합니다.
- 사용자 정보 조회 시 민감한 개인정보를 반환하지 않도록 처리했습니다
- 사용하지 않는 민감한 API 를 제거했습니다.
[#161]
=> 내 정보 조회 API 이관 및 사용자 정보 조회 관련 작업

src/main/java/com/example/codebase/controller/MemberController.java, src/main/java/com/example/codebase/controller/TeamController.java, src/main/java/com/example/codebase/controller/TeamUserController.java, src/main/java/com/example/codebase/domain/member/dto/MemberResponseDTO.java, src/main/java/com/example/codebase/domain/member/entity/Member.java, src/main/java/com/example/codebase/domain/member/service/MemberService.java, src/main/java/com/example/codebase/domain/team/dto/TeamResponse.java, src/main/java/com/example/codebase/domain/team/repository/TeamUserRepository.java, src/main/java/com/example/codebase/domain/team/service/TeamUserService.java, src/test/java/com/example/codebase/controller/MemberControllerTest.java, src/test/java/com/example/codebase/controller/TeamControllerTest.java
- 내가 속한 팀 정보 api 응답 반환 데이터를 수정했습니다.
-> 해당 유저의 팀 권한 role에 대해서 추가했습니다.
```json
"teams": [
{
"id": 27,
"profileImage": "http://localhost:8080/swagger-ui/index.html#/%ED%8C%80%20API/createTeam",
"name": "1strin1g",
"role": "OWNER"
},
{
"id": 26,
"profileImage": "http://localhost:8080/swagger-ui/index.html#/%ED%8C%80%20API/createTeam",
"name": "strin1g",
"role": "OWNER"
},
{
"id": 28,
"profileImage": "http://localhost:8080/swagger-ui/index.html#/%ED%8C%80%20API/createTeam",
"name": "1st2rin1g",
"role": "OWNER"
}
```
- get /teams/members/{username} 
- get api/members/{username} 
- 타 서비스 (github)를 참고하니 가입한 팀(오래된) 순서대로 반환하는 것을 확인했습니다. 일관성 있는 반환을 위해 
@orderby와 jpa 쿼리 메소드를 사용하여 가입한 팀(오래된) 순서대로 반환하도록 했습니다.
> [jirra이슈](https://mediaxi.atlassian.net/jira/software/projects/ART/boards/1?selectedIssue=ART …
=> Art 184 be 내가 속한 팀 정보 api 응답 데이터 수정

.github/workflows/test.yaml, src/main/java/com/example/codebase/controller/MagazineCategoryController.java, src/main/java/com/example/codebase/domain/magazine/entity/MagazineCategory.java, src/main/java/com/example/codebase/domain/magazine/repository/MagazineCategoryRepository.java, src/main/java/com/example/codebase/domain/magazine/service/MagazineCategoryService.java, src/test/java/com/example/codebase/controller/MagazineCategoryControllerTest.java
1. parentId 없이 name, slug를 수정할때 에러가 발생하던 문제를 해결했습니다.
- 해당 문제는 name, slug 중복조건에서 자기 자신을 참조하는 문제가 있어 발생하는 에러였습니다.
2. artwork, parentId, slud 가 null일 경우에 발생하던 400에러를 해결하였습니다.
3. parentId로 자기 지신의 id를 집어넣을시 발생하던 stackoverflow문제를 해결했습니다.
4. 카테고리 수정시 api가 put에서 patch로 변경되었습니다.
[jirra이슈](https://mediaxi.atlassian.net/jira/software/projects/ART/issues/?jql=project%20%3D%20%22ART%22%20ORDER%20BY%20created%20DESC)
=> fix : 카테고리 수정 문제 해결

src/main/java/com/example/codebase/domain/magazine/entity/MagazineComment.java, src/main/java/com/example/codebase/domain/member/entity/Member.java
댓글 작성자인데 댓글 수정,삭제 시 요청이 처리가 되지 않는 문제를 해결했습니다.
isCommentAuthor 메서드는 두 객체의 참조값을 비교연산해 동일한 작성자인지를 체크하고 있었습니다.
하지만 MagazineComment의 Member 인스턴스는 실제로 LazyLoading 으로 인한 Proxy 객체 이므로 동일 비교 시 논리적으론 두 객체가 동일하지만 참조값이 달라서 문제가 발생했습니다.
따라서 이를 해결하기위해 equals 메서드를 재정의하였고 Primary Key 필드를 통해서 동등성 비교를 하도록 로직을 개선했습니다. 
https://mediaxi.atlassian.net/browse/ART-188?atlOrigin=eyJpIjoiMzliOGZlMTZlNWZmNDdmNWE1NmZlYmYyMWM2YjE2OTUiLCJwIjoiaiJ9
=> [Issue] 매거진 댓글 작성자가 수정, 삭제를 못하는 에러 해결

src/main/java/com/example/codebase/controller/MagazineController.java, src/main/java/com/example/codebase/domain/magazine/dto/MagazineRequest.java, src/main/java/com/example/codebase/domain/magazine/service/MagazineService.java, src/test/java/com/example/codebase/controller/MagazineControllerTest.java
> 매거진 수정시 MagazineRequest.Update에서 categorySlug가 null일경우 기존의 slug를 반영하도록 수정했습니다.
> 추후에 확장과 변경이 용이하도록 더 나은 magazineCategory를 조회 및 magazine에서 category를 수정하는 로직에 대해서 고민해보겠습니다.
[jirra이슈](https://mediaxi.atlassian.net/jira/software/projects/ART/issues/ART-187?jql=project%20%3D%20%22ART%22%20ORDER%20BY%20created%20DESC)
=> [Issue] 매거진 수정시 categorySlug가 null을 허용하도록 변경

src/main/java/com/example/codebase/controller/MemberController.java, src/main/java/com/example/codebase/domain/member/dto/ProfileUrlDTO.java, src/main/java/com/example/codebase/domain/member/entity/Member.java, src/main/java/com/example/codebase/domain/member/service/MemberService.java, src/test/java/com/example/codebase/controller/MemberControllerTest.java
S3 업로드가 아닌 URL을 받도록 멤버 프로필 이미지 변경 API  수정
https://mediaxi.atlassian.net/browse/ART-190
=> [issue] 내 프로필 이미지 변경 시 url 받도록 변경

src/main/java/com/example/codebase/domain/team/service/TeamUserService.java
- 팀 유저 직책 변경 api - > patch : team-users/{username} api 문제해결
> 직책 변경시 자기 자신이 변경되는 문제를 해결했습니다.
[jirra이슈](https://mediaxi.atlassian.net/jira/software/projects/ART/issues/ART-189?jql=project%20%3D%20%22ART%22%20ORDER%20BY%20created%20DESC)
=> fix: 직책 변경시 자기 자신이 변경되던 문제 해결

src/main/java/com/example/codebase/controller/TeamController.java, src/main/java/com/example/codebase/domain/team/dto/TeamResponse.java, src/main/java/com/example/codebase/domain/team/repository/TeamUserRepository.java, src/main/java/com/example/codebase/domain/team/service/TeamService.java, src/main/java/com/example/codebase/domain/team/service/TeamUserService.java, src/test/java/com/example/codebase/controller/MagazineControllerTest.java, src/test/java/com/example/codebase/controller/MemberControllerTest.java, src/test/java/com/example/codebase/controller/TeamControllerTest.java, src/test/java/com/example/codebase/controller/TeamUserControllerTest.java
- 팀 정보 조회시 팀장의 (owner)의 username을 반환하도록 수정했습니다.
- TeamService에 di를 받아서 
(예시 코드입니다)
이런식으로 메서드를 추가해서 리턴해버리면 
1. 변경되는 코드의 수를 줄임
2. team에 대해서 조회하는 쿼리를 줄임 (teamUser을 조회할 때 team은 fetch = fetchType.EAGER로 되어있으므로 해당 방식으로 하면 같은 트랜잭션으로 묶여 영속상태로 team을 가지고 있기 때문에 team을 다시 한번 조회하는걸 줄일 수 있음 )
---
- 하지만 방금 커밋한 방식대로 작업을 했습니다.
그 이유는
1. 각 메서드의 기존보다 행위를 명확하게 했습니다. 
2. 팀이 생성,수정의 행위와 팀을 조회하는 행위가 분리되어야 한다고 생각 했습니다. ( 수정된 response를 받지 못하더라도 team정보는 정상적으로 수정됨)
[jirra이슈](https://mediaxi.atlassian.net/jira/software/projects/ART/issues/?jql=project%20%3D%20%22ART%22%20ORDER%20BY%20created%20DESC)
해당 수정이 올바른 방향인지. 또한 더 좋은 방법이 있을지 궁금합니다.
=> feat : 팀 정보 조회시 owner의 username을 반환하도록 수정
